# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sentia_apn_sender"
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kali Donovan", "Mario Visic"]
  s.date = "2012-05-04"
  s.description = "Resque-based background worker to send Apple Push Notifications over a persistent TCP socket. Includes Resque tweaks to allow persistent sockets between jobs, helper methods for enqueueing APN notifications, and a background daemon to send them. Original gem by Kali Donovan and modified by Sentia."
  s.email = "mario.visic@sentia.com.au"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "contrib/apn_sender.monitrc",
    "generators/apn_sender_generator.rb",
    "generators/templates/script",
    "init.rb",
    "lib/apn.rb",
    "lib/apn/connection/base.rb",
    "lib/apn/feedback.rb",
    "lib/apn/notification.rb",
    "lib/apn/notification_job.rb",
    "lib/apn/queue_manager.rb",
    "lib/apn/queue_name.rb",
    "lib/apn/sender.rb",
    "lib/apn/sender_daemon.rb",
    "lib/apn/tasks.rb",
    "lib/resque/hooks/before_unregister_worker.rb",
    "lib/sentia_apn_sender.rb",
    "rails/init.rb",
    "sentia_apn_sender.gemspec",
    "test/helper.rb",
    "test/test_apple_push_notification.rb"
  ]
  s.homepage = "https://github.com/sentia/apn_sender"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "Resque-based background worker to send Apple Push Notifications over a persistent TCP socket. Original gem by Kali Donovan and modified by Sentia."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 0"])
      s.add_runtime_dependency(%q<resque-access_worker_from_job>, [">= 0"])
    else
      s.add_dependency(%q<resque>, [">= 0"])
      s.add_dependency(%q<resque-access_worker_from_job>, [">= 0"])
    end
  else
    s.add_dependency(%q<resque>, [">= 0"])
    s.add_dependency(%q<resque-access_worker_from_job>, [">= 0"])
  end
end

